### ISSUE TITLE
 Directive FilePickerDirective, Property 'browse' is private and only accessible within class 'FilePickerDirective'.

### ISSUE THREAD

**Issue by fmq** [fvilers/ngx-file-helpers#9]
Version: 1.0.0-alpha.5

I'm using this library inside an Angular 6 library and when I compile the library I'm getting the following error:

```Building Angular Package
Building entry point '@condo/components'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
projects/condo/components/src/lib/file-selector/file-selector.component.ts.FileSelectorComponent.html(6,1): : Directive FilePickerDirective, Property 'browse' is private and only accessible within class 'FilePickerDirective'.

Error: projects/condo/components/src/lib/file-selector/file-selector.component.ts.FileSelectorComponent.html(6,1): : Directive FilePickerDirective, Property 'browse' is private and only accessible within class 'FilePickerDirective'.

    at Object.<anonymous> (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

projects/condo/components/src/lib/file-selector/file-selector.component.ts.FileSelectorComponent.html(6,1): : Directive FilePickerDirective, Property 'browse' is private and only accessible within class 'FilePickerDirective'.

Error: projects/condo/components/src/lib/file-selector/file-selector.component.ts.FileSelectorComponent.html(6,1): : Directive FilePickerDirective, Property 'browse' is private and only accessible within class 'FilePickerDirective'.

    at Object.<anonymous> (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /Users/fmq/workspace/et/condo/condo-ng/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

I temporarily made property "browse" public and it fixed the error.

Angular Version:

```
Angular CLI: 6.1.0
Node: 9.11.0
OS: darwin x64
Angular: 6.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.7.0
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.7.0
@angular-devkit/build-webpack      0.7.0
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.7.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.0
@schematics/angular                0.7.0
@schematics/update                 0.7.0
ng-packagr                         3.0.3
rxjs                               6.2.2
typescript                         2.7.2
webpack                            4.9.2
    
```

**Comment by fvilers** [comment]
Hi, do you try to access the `browse` method from your application? You shouldn't, hence why it's private. It's just a method to simulate a click on the hidden file input.

**Comment by fvilers** [comment]
A new release tagged `1.0.0-alpha.6` is available on NPM. Thanks for your help.
